### ISSUE TITLE
"Linux" binary is a windows executable

### ISSUE THREAD

**Issue by vbedesu** [NovaSquirrel/Mesen-SX#62]
On the releases section, there is a file named "Mesen-S-Linux.zip"; I extracted it and got a windows executable instead.

**Comment by NovaSquirrel** [comment]
It doesn't work when you attempt to run it with Mono?

**Comment by vbedesu** [comment]
Seems like that worked, my bad

**Comment by NovaSquirrel** [comment]
I'll put a note somewhere that you have to use mono
